#!/usr/bin/env python3
import os
import shutil
import sys
import zipfile
import pdfkit
import settings

if len(sys.argv) not in [2, 3]:
    print("Usage: ./scripts/kattis_open problemname [language]")
    print("The language is cpp by default and can be either 'cpp' or 'py'")
    exit(0)

language = 'cpp'
if len(sys.argv) == 3 and sys.argv[2] == "py":
    language = 'py'

problemname = sys.argv[1]
problem_dir = os.path.join(settings.relative_problem_path, problemname)


problem_path = os.path.join(problem_dir, '{}.{}'.format(problemname, language))

problem_solution = os.path.join(
    problem_dir, '{}.md'.format(problemname))
problem_description = os.path.join(
    problem_dir, '{}.pdf'.format(problemname))

problem_test = os.path.join('tests', problemname)

try:
    os.mkdir(problem_dir)
except FileExistsError:
    print("'{}' already exists, are you sure you want to create it?".format(problemname))
    exit(1)

try:
    os.mkdir(problem_test)
except FileExistsError:
    print("Test folder already exists")

shutil.copyfile(os.path.join(
    settings.relative_library_path, 'template.{}'.format(language)), problem_path)

with open(problem_solution, 'w') as f:
    print("# Problem Type", file=f)
    print("", file=f)
    print("# Proposed solution", file=f)
    print("", file=f)
    print("## Solution complexity", file=f)
print("'{}' was successfully opened, time to get solving!".format(problemname))

sample_url = 'https://open.kattis.com/problems/{}/file/statement/samples.zip'
problem_url = 'https://open.kattis.com/problems/{}/'
url = sample_url.format(problemname)
url2 = problem_url.format(problemname)

# For some reason python http lib gets 403 forbidden ??? Just use wget instead -.-
os.system('wget -q {}'.format(url))
pdfkit.from_url(url2, problem_description)

try:
    local_zip = 'samples.zip'
    f = zipfile.ZipFile(local_zip)
    f.extractall(problem_test)
    os.remove(local_zip)

    print("Samples fetched from kattis and put into tests folder")
except:
    print('Could not download sample input.'
          + ' Perhaps none exist on Kattis or you do not have internet connection?')
